# myApp/docker-compose.yaml
services:
  postgres:
    build:
      context: .
      dockerfile: ./data/Dockerfile
    container_name: postgres
    restart: unless-stopped
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data  
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    user: "${UID}:${GID}" 
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: danielbergmorais@outlook.com
      PGADMIN_DEFAULT_PASSWORD: bergdev
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - internal
volumes:
  data:
networks:
  internal:
    driver: bridge